name: HawkScan
# on:
#   push:
#   pull_requests:
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Stand up app 
        uses: actions/checkout@v2
        run: docker-compose up -d
      - name: Run HawkScan
        id: run-hawkscan
      env:
        APP_HOST: 'http://localhost:5000'
        APP_ID: AE624DB7-11FC-4561-B8F2-2C8ECF77C2C7
        APP_ENV: Development
      uses: stackhawk/hawkscan-action@v2.2.0
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}
        configurationFiles: |
          stackhawk.yml
          stackhawk-extras.yml
