name: HawkScan
on:
  push
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Java versioning
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download and run JavaSpringVulny release jar
        run: |
          curl -Ls https://github.com/kaakaww/javaspringvulny/releases/download/0.2.0/java-spring-vuly-0.2.0.jar -o ./java-spring-vuly-0.2.0.jar
          java -jar ./java-spring-vuly-0.2.0.jar &
#      - name: Build and run JavaSpringVulny (slower)
#        run: |
#          ./gradlew build
#          ./gradlew bootRun &
      - name: Get the Repo
        uses: actions/checkout@v4
        
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          APP_ID: 9fe41c6b-6a52-461f-afd8-27b8530159fe
          SARIF_ARTIFACT: true
      - name: Collect hawkscan log
        uses: actions/upload-artifact@v4
        with:
          name: stackhawk_logs
          path: '~/.hawk/sessions/**/hawkscan.log'
